// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpjykbcejybolqxomkyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwanlrYmNlanlib2xxeG9ta3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDY2OTksImV4cCI6MjA2ODQ4MjY5OX0.CzFxb5P3kuVTrsVjUK0YzHFlAtnMIrj7IzHU-jaemkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});